### ISSUE TITLE
what if a cell is visited more than 18 times?

### ISSUE THREAD

**Issue by beenotung** [atoponce/keyart#6]
I have implemented the original version describped in your blog,
repo at https://github.com/beenotung/randomart.

I used below script to find out it is possible for a cell to be visited 16 times. I see you redeisgned the frequency table, but still wonder if it is possible to hit the limit?
```
set -e
set -o pipefail
touch /tmp/a
while true; do
  randomart /tmp/a | tee /tmp/b
  mv /tmp/b /tmp/a
done
```

**Comment by beenotung** [comment]
Attached the file causing this bug [a.txt](https://github.com/atoponce/keyart/files/2174561/a.txt)
```
+-----------------+
|        +oB*===o |
|       o.*oO=+=E |
|      . =.. Booo.|
|     . . .   B  o|
|      . S   + + +|
|     . .   . = o |
|      o o . . .  |
|     . o o .     |
|      . ...      |
+----[SHA256]-----+
```

**Comment by atoponce** [comment]
I'm not sure what the bug is. Can you describe it more clearly? If you reach a cell more than 18 times, it'll just continue to draw the "@" character in that cell.

As an example, we could draw a diamond around the room. Starting with the first 8 bytes:

    $ keyart -f 50FFAA00
    +-------------------+
    |                   |
    |         .         |
    |        . .        |
    |       .   .       |
    |        .   .      |
    |     E   S   .     |
    |      .     .      |
    |       .   .       |
    |        . .        |
    |         .         |
    |                   |
    +-------------------+

Twice around:

    $ keyart -f 50FFAA0055FFAA00
    +-------------------+
    |                   |
    |         ^         |
    |        ^ ^        |
    |       ^   ^       |
    |      . .   ^      |
    |     E   S   ^     |
    |      ^     ^      |
    |       ^   ^       |
    |        ^ ^        |
    |         ^         |
    |                   |
    +-------------------+

Three times:

    $ keyart -f 50FFAA0055FFAA0055FFAA00
    +-------------------+
    |                   |
    |         :         |
    |        : :        |
    |       :   :       |
    |      ^ .   :      |
    |     E   S   :     |
    |      :     :      |
    |       :   :       |
    |        : :        |
    |         :         |
    |                   |
    +-------------------+

Wash, rinse, repeat, and 18 times:

    $ keyart -f 50FFAA0055FFAA0055FFAA0055FFAA0055FFAA0055FFAA0055FFAA0055FFAA0055FFAA0055FFAA0055FFAA0055FFAA0055FFAA0055FFAA0055FFAA0055FFAA0055FFAA0055FFAA00
    +-------------------+
    |                   |
    |         @         |
    |        @ @        |
    |       @   @       |
    |      % .   @      |
    |     E   S   @     |
    |      @     @      |
    |       @   @       |
    |        @ @        |
    |         @         |
    |                   |
    +-------------------+

What happens the 19th time around? Nothing really interesting. The "%" is converted to "@", but other than that:

    $ keyart -f 50FFAA0055FFAA0055FFAA0055FFAA0055FFAA0055FFAA0055FFAA0055FFAA0055FFAA0055FFAA0055FFAA0055FFAA0055FFAA0055FFAA0055FFAA0055FFAA0055FFAA0055FFAA0055FFAA00
    +-------------------+
    |                   |
    |         @         |
    |        @ @        |
    |       @   @       |
    |      @ .   @      |
    |     E   S   @     |
    |      @     @      |
    |       @   @       |
    |        @ @        |
    |         @         |
    |                   |
    +-------------------+

**Comment by beenotung** [comment]
so we don't distinct 18 and 18+, right?
(same as age restricted policy lol)

**Comment by atoponce** [comment]
Heh, right. Any cell that sees 18 or more "coins" will get "@", regardless.
